### PR TITLE
Update action-group.yml

### PR DESCRIPTION
**Pull request by quillanogle**

### CODE REVIEW

**Comment by quillanogle** [comment]
I'm not sure how to update so that this YAML file is updated properly but there are 2 broken tables on this page

**Comment by quillanogle** [comment]
@AbbyMSFT would you be able to help me make the right changes in the right place?

**Comment by AbbyMSFT** [comment]
Hi @quillanogle ,
Thanks for noticing and bringing this to our attention.
CLI docs are auto-generated, so I don't have a way of fixing the formatting. I have reached out to the owners of the CLI docs to see how we can address the issue. You are on the cc.

Thanks,
Abby

**Comment by quillanogle** [comment]
[heart]         Quillan Ogle reacted to your message:
________________________________

**Comment by dbradish-microsoft** [comment]
@quillanogle , This update needs to be made in https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py, and then it will be published to azure-docs-cli.

**Comment by quillanogle** [comment]
> @quillanogle , This update needs to be made in https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py, and then it will be published to azure-docs-cli.

Thank you, I believe I have made the proper request in #29747

**Pull request closed without merging**
