### PR TITLE
BatchAI: Adding deprecation text

### PR DESCRIPTION
**Pull request by garyericson**
Adding text to description to announce deprecation of Batch AI.

### CODE REVIEW

**Comment by garyericson** [comment]
#sign-off

**Comment by garyericson** [comment]
#hold-off - Need to try one more tweak.

**Comment by sptramer** [comment]
This change would be overwritten in the next automated documentation release with 2.0.61, slated for __today__. Please file a support request with the engineering team regarding deprecation messages in online docs, although I believe they already have this on their roadmap. https://github.com/azure/azure-cli/issues

**Comment by garyericson** [comment]
@sptramer - Thanks for your note. I just took a stab in the dark here because I can't find any documentation on how to do what I'm trying to do. I took a guess and tried to follow something similar that seemed to be done in other content sets. 

How do I file a support request with the engineering team?

**Comment by sptramer** [comment]
File an issue on github: https://github.com/azure/azure-cli/issues

**Comment by garyericson** [comment]
@sptramer - Thanks. Do I file it under "Bug report", "Feature request", or "Service Team Support Request"? (the choices given when you select New Issue)

**Comment by sptramer** [comment]
I would consider this a feature request since it is an improvement to the existing docs ref publishing pipeline.

**Pull request closed without merging**
