### PR TITLE
Create new article summarizing CLI references for Azure Storage

### PR DESCRIPTION
**Pull request by dksimpson**
This work is for story [1829816](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1829816).

### CODE REVIEW

**Comment by dbradish-microsoft** [comment]
@dksimpson , please take this out of Draft move when it is ready to Merge.

**Comment by dksimpson** [comment]
Hi @dbradish-microsoft, I've just added some more references - this PR is now ready for review.

**Comment by dbradish-microsoft** [comment]
@dksimpson , I'm not seeing the connection between `az storagesync registered-server` and the article you have linked for more information.  Where in [that article](https://docs.microsoft.com/en-us/azure/storage/file-sync/file-sync-deployment-guide?tabs=azure-cli%2Cproactive-portal) is this reference command used?

image

**Comment by dksimpson** [comment]
@dbradish-microsoft, you're correct, `az storagesync registered-server` isn't used specifically in that article. I included the article because there wasn't anything else available. I can remove it.

**Comment by dbradish-microsoft** [comment]
@dksimpson , If a reference isn't used in an article, please leave the information column blank.  Every information link should have at least one example of how to use that specific command.  Please circle back through your other summary pages and confirm that each command reference is represented in the linked article.  Thanks!!

**Comment by dksimpson** [comment]
Hi @dbradish-microsoft, I've reviewed all the info links and removed links to those articles that don't contain specific Azure CLI examples. Ready for review.

**Pull request merged**
