### PR TITLE
Update release notes link for ml

### PR DESCRIPTION
**Pull request by kingernupur**
Update release notes link for ml

### CODE REVIEW

**Review by Blackmist — APPROVED** [review]

**Review by Blackmist — APPROVED** [review]

**Comment by Blackmist** [comment]
#sign-off

**Comment by s-polly** [comment]
#sign-off

**Comment by dbradish-microsoft** [comment]
@kingernupur, I appreciate this update (REALLY!) as we are working to reduce our build validation errors; however, this article is autogenerated from source code. Any changes to this doc will be overwritten later on today or tomorrow.

To modify the link, the change must take place in Azure/azure-cli-extensions, or one of the extension repos owned by the ML service team. In the repos I scan, I'm not finding this URL in source code, so the ML source code must be in a repo I'm not reading.

**Comment by kingernupur** [comment]
Thanks, @dbradish-microsoft!
ml is indeed not open source. To ensure that I make the correct changes, can you link me to this file generation script?

**Comment by dbradish-microsoft** [comment]
@bebound, can you please direct @kingernupur to the correct place to change information in release notes?

**Pull request closed without merging**
