### PR TITLE
Azure Rest Tutorial for Azure CLI

### PR DESCRIPTION
**Pull request by daphnemamsft**

### CODE REVIEW

**Comment by jiasli** [comment]
I don't feel the necessity of splitting the content into 4 parts. Maybe one page should suffice?

**Comment by dbradish-microsoft** [comment]
@jiasli, This is a draft pull request.  Let's let Daphne finish and then see what the content looks like.

**Review by dbradish-microsoft — CHANGES_REQUESTED** [review]

**Comment by dbradish-microsoft** [comment]
@jiasli, This PR is ready for technical review.  It is trimmed down to a one page How-to guide.

**Comment by dbradish-microsoft** [comment]
Merging PR as sufficient time left for additional review.  Code blocks have been tested successfully by ms.author.

**Comment by daphnemamsft** [comment]
#sign-off

**Pull request merged**
