### PR TITLE
1794696 navigation - subscriptions

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
[1794696](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1794696), linked to 177411.

@dbradish-microsoft is looking at this now.

### CODE REVIEW

**Comment by dbradish-microsoft** [comment]
@TimShererWithAquent , information we acquired from the email thread with the subject "Looking for clarity on default subscription information" needs to be added to this document.  How about a new H2 right after H2 "Tenants ..." and before H2 "Change the active..."?

**Comment by TimShererWithAquent** [comment]
Restarting. There was an issue in builds when I updated this before.

**Comment by TimShererWithAquent** [comment]
and reopen.

**Comment by TimShererWithAquent** [comment]
@dbradish-microsoft 

I've added a section about knowing what subscription you are in. Along with the resource group topic, I think we've covered info from that email thread.

**Comment by dbradish-microsoft** [comment]
@TimShererWithAquent , please convert this to a PR so I can merge.  Thank you.

**Pull request merged**
