### PR TITLE
Add "az search" to titleMapping.json

### PR DESCRIPTION
**Pull request by timothyta12**

### CODE REVIEW

**Comment by timothyta12** [comment]
@MicrosoftDocs/azure-dev-docs-admin (I think this is the right alias) could someone please review this PR.

**Comment by timothyta12** [comment]
@dbradish-microsoft, @daxianji007, I see that you have merged previous PR's for this particular file. Would you be able to review this PR or link someone that can?

**Comment by dbradish-microsoft** [comment]
@timothyta12 , Unless a methodology has changed, you don't need to add entries to titleMapping.json unless the tocTitle is different than the pageTitle.  The purpose of this file is to improve the Azure CLI Reference navigation.

**Comment by timothyta12** [comment]
@dbradish-microsoft, how would I get "search" to look like "Search" in the table of contents? Similar to the other services such as "App Service", "Azure Active Directory", "SQL", and "Storage" in the link below?

https://docs.microsoft.com/en-us/cli/azure/search?view=azure-cli-latest

**Comment by timothyta12** [comment]
@dbradish-microsoft, could I get a response to my prior question? Thanks.

**Comment by dbradish-microsoft** [comment]
Hello, @timothyta12, your update is fine.  We are working to implement a new mapping file that will have 100% of TOC content (both core and extension combined) along with lots of other good information, like Azure service name.  In the interim, keep on keeping on.

**Pull request merged**
