### PR TITLE
Message fixing: 'preserve-view-not-set', small PR first.

### PR DESCRIPTION
**Pull request by MightyPen**
Message fixing: 'preserve-view-not-set', small PR first, #2325.

My contact on this FTE writing team is **Delora Bradish**.

C# program `PreserveView2a.exe` fixed these few files in this small scale "bulk" PR. The next runs of this .exe will fix hundreds of these files per run.

Understand that instances of this Suggestion/Warning message type = 'preserve-view-not-set' DO exist in this repo `azure-docs-cli`, even though we are currently suppressing this type so that the instances are kept out of the PR Build Report. We will cease suppressing the display of this type when the count of its occurrences is greatly decreased across MartinEk's entire org.

GeneMi (= MightyPen)

### CODE REVIEW

**Comment by MightyPen** [comment]
For my own (GeneMi) later reference, here is some output from the .exe, about odd Link syntax, to maybe fix by hand.

Why have the `?` character that indicates the first URL parameter, when there are zero URL parameters in the link?

---

( C# , PreserveView2a.exe )

Mesg_Warning_nv48j2:  File has illegal link syntax, skipping. FileOne= 'C:\Users\genemi\GitGm\azure-docs-cli\docs-ref-conceptual\create-an-azure-service-principal-azure-cli.md' , Line= '* [az login](/cli/azure/reference-index?#az_login)' , Link= '[az login](/cli/azure/reference-index?#az_login)' , UrlParameter= '#az_login'.

Mesg_Warning_nv48j2:  File has illegal link syntax, skipping. FileOne= 'C:\Users\genemi\GitGm\azure-docs-cli\docs-ref-conceptual\param-persist-howto.md' , Line= '[Install the Azure CLI](install-azure-cli.md) or open [Azure Cloud Shell](https://shell.azure.com) to run the scripts in this article.  If you are using a local install of the Azure CLI, version 2.12.0 or later is needed to run **az config param-persist** commands.  Run [az version](/cli/azure/reference-index?#az_version) to find the version and dependent libraries that are installed. To upgrade to the latest version, run [az upgrade](/cli/azure/reference-index?#az_upgrade).  Azure Cloud Shell always has the latest version of the Azure CLI.' , Link= '[az version](/cli/azure/reference-index?#az_version)' , UrlParameter= '#az_version'.

Mesg_Warning_nv48j2:  File has illegal link syntax, skipping. FileOne= 'C:\Users\genemi\GitGm\azure-docs-cli\docs-ref-conceptual\param-persist-howto.md' , Line= '[Install the Azure CLI](install-azure-cli.md) or open [Azure Cloud Shell](https://shell.azure.com) to run the scripts in this article.  If you are using a local install of the Azure CLI, version 2.12.0 or later is needed to run **az config param-persist** commands.  Run [az version](/cli/azure/reference-index?#az_version) to find the version and dependent libraries that are installed. To upgrade to the latest version, run [az upgrade](/cli/azure/reference-index?#az_upgrade).  Azure Cloud Shell always has the latest version of the Azure CLI.' , Link= '[az upgrade](/cli/azure/reference-index?#az_upgrade)' , UrlParameter= '#az_upgrade'.

Mesg_Warning_nv48j2:  File has illegal link syntax, skipping. FileOne= 'C:\Users\genemi\GitGm\azure-docs-cli\docs-ref-conceptual\param-persist-tutorial.md' , Line= '    - This tutorial requires version 2.12.0 or later of the Azure CLI.  Run [az version](/cli/azure/reference-index?#az_version) to find the version and dependent libraries that are installed. To upgrade to the latest version, run [az upgrade](/cli/azure/reference-index?#az_upgrade).' , Link= '[az version](/cli/azure/reference-index?#az_version)' , UrlParameter= '#az_version'.

Mesg_Warning_nv48j2:  File has illegal link syntax, skipping. FileOne= 'C:\Users\genemi\GitGm\azure-docs-cli\docs-ref-conceptual\param-persist-tutorial.md' , Line= '    - This tutorial requires version 2.12.0 or later of the Azure CLI.  Run [az version](/cli/azure/reference-index?#az_version) to find the version and dependent libraries that are installed. To upgrade to the latest version, run [az upgrade](/cli/azure/reference-index?#az_upgrade).' , Link= '[az upgrade](/cli/azure/reference-index?#az_upgrade)' , UrlParameter= '#az_upgrade'.

---

Mesg_Warning_nd27f3:  Odd case caused (caught) Exception in FileOne= 'C:\Users\genemi\GitGm\azure-docs-cli\docs-ref-conceptual\includes\cloud-shell-try-it.md', Line= '| Open Cloud Shell in your browser. | [https://shell.azure.com/bash](https://shell.azure.com/bash) |'. Will NOT modify this Line.

Mesg_Exception_nd27f4: 'Length cannot be less than zero.
Parameter name: length'

**Comment by MightyPen** [comment]
@dbradish-microsoft @DCtheGeek 
Hello Delora and David,
_**Request:**_ &nbsp; Can you please formally Review this PR #2325, and either Approve or Reject it. I am hoping to Merge this PR Thursday morning.

This PR #2325 removes some URL parameters, from some links in some files. These URL parameters are `?view=azure-cli-latest` mostly. They are being removed because:

- This Versioning moniker value is the Default value for its Family; and
- The alternative fix is to add URL parameter `&preserve-view=true`, which consensus is inappropriate for Default monikers.

Thanks a lot.  GeneMi. &nbsp; 2020/Dec/03 03:24am Thursday

**Review by dbradish-microsoft — APPROVED** [review]
@MightyPen , I cannot speak to the removal of  **?view=azure-ml-py** or **?view=azure-devops**, but the removal of **?view=azure-cli-latest** is as anticipated.  This PR does not reflect the removal of **?view=azure-cli-latest&preserve-view=true**, which is also appropriate.  (Not sure if you intended this PR to be one of every change)

**Comment by MightyPen** [comment]
I double-checked the status of every Versioning moniker that this bulk automation run removed, and yes they are all Defaults.

I also checked the Before vs After links, and both links in every pair behave the same as each other.

MERGING now.

**Pull request merged**
