### PR TITLE
Fix CentOS version

### PR DESCRIPTION
**Pull request by bebound**
The last official version is 2.38.
Same as https://github.com/MicrosoftDocs/azure-docs-cli/pull/3567

### CODE REVIEW

**Review by dbradish-microsoft — APPROVED** [review]
@Bebond, @dcaro told me v 2.39, but you are closer to the facts.  I'm approving but have added @dcaro as a reviewer.

**Comment by bebound** [comment]
Here is repo for centos7 and 2.38 is the latest version.
https://packages.microsoft.com/yumrepos/azure-cli/Packages/a/

**Review by dcaro — CHANGES_REQUESTED** [review]
Pending confirmation

**Comment by dbradish-microsoft** [comment]
@dcaro / @bebound , Have we resolved this conversation?

**Comment by dcaro** [comment]
@dbradish-microsoft we are confirming that az cli *v2.38* is the last supported version for CentOS 7 and RHEL 7. This PR corrects a misunderstanding. It is always Microsoft's intent to communicate accurate information and we apologize for the confusion.

**Review by dcaro — APPROVED** [review]
LGTM

**Comment by dbradish-microsoft** [comment]
**This PR corrects a misunderstanding about the last Azure CLI version supported on RHEL 7 and Centos 7.  It is always Microsoft's intent to communicate accurate information and we apologize for the confusion.**

**Pull request merged**
