### PR TITLE
add "--subscription" in global pamaters

### PR DESCRIPTION
**Pull request by daxianji007**

### CODE REVIEW

**Comment by dbradish-microsoft** [comment]
@yonzhan, This is part of the reference autogeneration process.  If @daxianji007 has added it, I assume it should be merged.  What kind of feedback are you looking for from the other reviewers?

**Comment by daxianji007** [comment]
@dbradish-microsoft I confirmed with the dev team that every CLI command has a `--subscription` parameter. So, I will complete this PR.

**Comment by daxianji007** [comment]
@dbradish-microsoft Em... I see. This is added to all commands but some commands explictly ignored it. The Docs Pipeline currently does not support different "Global Parameters" for different commands (since it is 'global'). We can track this and implememt it when we have time to do kind of refactor.

**Comment by dbradish-microsoft** [comment]
CCing @chasewilson for awareness and I defer further discussion to the engineering team.

**Pull request merged**
