### PR TITLE
Updating TOC for Azure Policy commands

### PR DESCRIPTION
**Pull request by DCtheGeek**

### CODE REVIEW

**Comment by DCtheGeek** [comment]
#sign-off

**Comment by DCtheGeek** [comment]
@rloutlaw Is this a repo you review/approve for?

**Comment by DCtheGeek** [comment]
@dbradish-microsoft Can you review/merge this?

**Comment by dbradish-microsoft** [comment]
@DCtheGeek , the Azure CLI reference docs are auto-generated and the changes made by this PR will be overwritten.  

@fengzhou-msft  / @yonzhan , can you please help David C to make these changes in the appropriate _help.py file?  Thank you.

**Comment by yonzhan** [comment]
@dbradish-microsoft Xing will help with this.

**Comment by fengzhou-msft** [comment]
@zhoxing-ms did some check in the doc update pipeline and this file is not covered and seems to be manually written. Let's merge this PR first.

**Comment by zhoxing-ms** [comment]
Yes, I have seen the modification records of titleMapping.json are manually modified by others, and there is no modification record from the CI task of azure-cli.
If there is anything missing, please help to point it out @dbradish-microsoft

**Pull request merged**
