### PR TITLE
Update sign in with a managed identity

### PR DESCRIPTION
**Pull request by fengzhou-msft**
Tested on a vm, if the vm has 2 user assigned managed identities and no system assigned identity, use `az login --identity` without `--username` will get the following error:

> Failed to connect to MSI. Please make sure MSI is configured correctly. Get Token request returned http error: 400, reason: Bad Request

This is mentioned in [Use managed identities on VMs - Get a token using HTTP](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http).

A test for the vm that has 2 user assigned managed identities plus system assigned identity showed that `az login --identity` will login with the system assigned idenity, thus `--username` is not required in this case.

The doc is modified accordingly based on the above results.

### CODE REVIEW

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
Can we also update error message?

**Comment by fengzhou-msft** [comment]
> Can we also update error message?

It depends on the service error message. Currently, the service is returning the same error message when there is no identity or 2 user assigned identities. It is hard for us to distinguish the 2 cases.

**Pull request merged**
