### PR TITLE
Update install-azure-cli-windows.md

### PR DESCRIPTION
**Pull request by JUUTC**
Fix for issue: #3028

### CODE REVIEW

**Comment by JUUTC** [comment]
@jiasli Please review.

**Comment by chasewilson** [comment]
Hey @yonzhan, would it be possible to get a confirmation on these details? Thanks :)

**Comment by jiasli** [comment]
I don't think this is necessary as Windows will automatically choose the latest TLS version that is available. In the latest Windows 10 and Windows 11, TLS 1.2 will be used.

**Comment by jiasli** [comment]
This issue is too general and can happen to any non-standard Windows connecting to Azure Storage account. Let's close this PR for now. If we see more occurrences of this issue, we will reconsider it.

**Pull request closed without merging**
